### ISSUE TITLE
【質問】ブランチの切り方について

### ISSUE THREAD

**Issue by a1852rw** [a1852rw/shinatora_enpit#10]
ブランチ一覧ページを見ました
https://github.com/a1852rw/shinatora_enpit/branches

ここで質問です。
・私(a1952rw)は毎回同じ名前のブランチを使用
・皆さんは「アカウント名_日付」の名前で毎回ブランチ名を変更

作業の内容をわかりやすくするため、私も皆さんと同じ「アカウント名_日付」で都度ブランチを切るべきでしょうか？
ぜひとも教えていただきたく。

**Comment by jin-aiit-a1824jj** [comment]
じん
a1824jj_20180720 
です！

**Comment by a16z8yy** [comment]
ブランチについては承知しました。
山川 a16z8yy_20180720 です。

**Comment by a1852rw** [comment]
承知しました。
今後は　アカウント名_日付 でブランチを切ります。

このIssueはクローズにします。
