### ISSUE TITLE
【検討事項】ベースアプリの拡張方向性(7/20)

### ISSUE THREAD

**Issue by a1852rw** [a1852rw/shinatora_enpit#12]
・チームメンバーと拡張の方法性について検討する。

rw：issueにコンバートします(2018/7/20)

**Comment by a16z8yy** [comment]
メッセージの保存はスレッド単位であり、スレッドには番号をアサインされてあることから、スレッドの削除機能を追加してはいかがでしょうか。但し、ログインの認証がないので、削除はどなたでも可能にします。

**Comment by a1852rw** [comment]
アプリの開発は無事に終了しました。
このIssueはCloseにします。
