### ISSUE TITLE
【実施事項】slackとTravisCIの連携

### ISSUE THREAD

**Issue by a1852rw** [a1852rw/shinatora_enpit#16]
デプロイ後のテストの結果をSlackに送信するよう設定する
この作業とやり方の調査はrwが担当する。

作業手順については後程wikiに記載の予定。

**Comment by a1852rw** [comment]
この部分明日(7/24)に作業し、可能であれば24日の講義開始前に終わらせておこうと思います。
間に合わないそうであれば改めてここに書き込みます。

**Comment by jin-aiit-a1824jj** [comment]
https://qiita.com/nwtgck/items/17840855cb76f60fa1fe
参考記事です。

**Comment by a1852rw** [comment]
slackのプライベートチャンネルに結果が送信されること確認しました。
このIssuneはCloseにします。
