### ISSUE TITLE
【対応項目】複数の人が同時にメッセージの書き込み対応

### ISSUE THREAD

**Issue by a16z8yy** [a1852rw/shinatora_enpit#25]
複数の人が同時にメッセージを書き込む時に、Submitしない限り、他人のメッセージが画面に表示できない。ブラウザーのリフレッシュボタンによる更新機能が働かない。

**Comment by a1852rw** [comment]
画面上に「reload」ボタンを追加することでとりあえずは回避できました。
このissueをCloseにします。
