### ISSUE TITLE
【レビュー依頼】作業開始前チェックリスト

### ISSUE THREAD

**Issue by a1852rw** [a1852rw/shinatora_enpit#9]
作業開始前チェックリストアップしました。
このIssueページの他に、リポジトリ内のdocumentフォルダにも入れてあります。

[collaborative_checklist_2018_07_19_001.xlsx](https://github.com/a1852rw/shinatora_enpit/files/2207549/collaborative_checklist_2018_07_19_001.xlsx)
[collaborative_checklist_2018_07_19_001.pdf](https://github.com/a1852rw/shinatora_enpit/files/2207550/collaborative_checklist_2018_07_19_001.pdf)

■documentフォルダURL
https://github.com/a1852rw/shinatora_enpit/tree/master/document

レビューお願いできますでしょうか？

**Comment by a16z8yy** [comment]
作業開始前チェックリストの作成、ありがとうございます。
会話で確認できましたので、問題ありません。

**Comment by jin-aiit-a1824jj** [comment]
現時点では特に足りない部分がないと思います！

作成、お疲れ様でした！

**Comment by a1852rw** [comment]
了解です、あとでこのIssueをクローズしておきます。
